### ISSUE TITLE
The mobile attestation controller should remote log

### ISSUE THREAD

**Issue by jleach** [bcgov/mobile-attestation-vc-controller#63]
The attestation controller should support remote logging so that a log aggregation system like Loki can collect and correlate logs. I think the easiest way to get this up-and-running is to deploy a [Promtail sidecar](https://medium.com/@t-velmachos/deploy-promtail-as-a-sidecar-to-you-main-app-6182fa27db65) to our controller to slurp up logs.

**Comment by cvarjao** [comment]
duplicates #58
